name: "Publish to GitHub Pages"

env:
  GODOT_VERSION: 4.1.2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    container:
      image: barichello/godot-ci:4.1.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move HTML5 templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Create staging directory
        run: mkdir -v -p builds/web

      - name: Build
        run: godot -v --export-release --headless "Web" ../builds/web/build2.html project/project.godot

      - name: Add COI Service Worker
        run: |
          wget https://coi-serviceworker.pages.dev/coi-serviceworker.js -O builds/web/coi-serviceworker.js
          awk '/<head>/{print; print "    <script src=\"coi-serviceworker.js\"></script>"; print "    <script>if (typeof window !== \x27undefined\x27 && \x27serviceWorker\x27 in navigator) { navigator.serviceWorker.register(\x27coi-serviceworker.js\x27); }</script>"; next}1' builds/web/build2.html > builds/web/tmp.html
          awk '/<head>/{print; print "    <script src=\"coi-serviceworker.js\"></script>"; print "    <script>if (typeof window !== \x27undefined\x27 && \x27serviceWorker\x27 in navigator) { navigator.serviceWorker.register(\x27coi-serviceworker.js\x27); }</script>"; next}1' builds/web/index.html > builds/web/indextmp.html
          mv builds/web/tmp.html builds/web/build2.html
          mv builds/web/indextmp.html builds/web/index.html
          



      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builds/web
          force_orphan: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish to gh-pages"
